{% set version = "0.0.6" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 3958d853681f703c0e5a473754d558e6c0380251bb00970d025489b7eef3e690

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - properscoring
    - scikit-learn
    - scipy
    - xarray
    - numba
    - bottleneck

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/raybellwaves/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
