{% set version = "0.0.5" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 1e6bfab7994f77307fbf3926a49ee5639908596cb52c8eab6d76b44cdd8eea07

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - properscoring
    - scikit-learn
    - scipy
    - xarray
    - numba

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/raybellwaves/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
